export const Permissions = {
    ADMINISTRATOR: 'Administrator',
    CATALOG: 'Catalog',
    CATALOG_MANAGER: 'Catalog.Manager',
    CHARGE: 'Charge',
    CHARGE_MANAGER: 'Charge.Manager',
    DEVICE: 'Device',
    DEVICE_MANAGER: 'Device.Manager',
    FACILITY: 'Facility',
    FACILITY_MANAGER: 'Facility.Manager',
    FULFILLMENT: 'Fulfillment',
    FULFILLMENT_MANAGER: 'Fulfillment.Manager',
    INVOICE: 'Invoice',
    INVOICE_MANAGER: 'Invoice.Manager',
    JOB: 'Job',
    JOB_MANAGER: 'Job.Manager',
    MERCHANDISER: 'Merchandiser',
    MERCHANDISER_MANAGER: 'Merchandiser.Manager',
    ORDER: 'Order',
    ORDER_MANAGER: 'Order.Manager',
    ORG_ADMINISTRATOR: 'Org.Administrator',
    TIMETRACKING: 'TimeTracking',
    TIMETRACKING_MANAGER: 'TimeTracking.Manager',
    USER: 'User',
    USER_MANAGER: 'User.Manager',
    WAREHOUSE: 'Warehouse',
    WAREHOUSE_MANAGER: 'Warehouse.Manager',
  } as const;
  